### PR TITLE
fix(DatesRangeInput): error when allowed range doesn't contain today

### PR DESCRIPTION
**Pull request by arfedulov**

### CODE REVIEW

**Comment by sevketriza** [comment]
i see that this fix about daterangeinput component. but this does not fix #127 issue   
but stiĺl it is closed?

**Comment by arfedulov** [comment]
It's not published on npm yet. Or did you build from master branch and that didn't work?

**Comment by sevketriza** [comment]
No i only saying according to df50d34 revision code changes. I saw code changes only in DateRangeInput not DateInput. Am I wrong?

**Comment by arfedulov** [comment]
Yes, you are right. I reopen an issue. Will fix it soon.

**Pull request merged**
